#!/bin/zsh

# Uncomment during development
# set -x

XRCDIR=$(cd `dirname $0` && pwd)

$XRCDIR/update
if [ $? -eq 2 ]; then
  echo "Found new version. Restarting."
  exec $XRCDIR/install
fi

which brew 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "Unable to find brew. Aborting."
  exit 1
fi

which nvim 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "Neovim not found, installing via brew"
  brew install neovim || exit 1
fi

which zoxide 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "zoxide not found, installing via brew"
  brew install zoxide || exit 1
fi

which eza 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "eza not found, installing via brew"
  brew install eza || exit 1
fi

which bat 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "bat not found, installing via brew"
  brew install bat || exit 1
fi

which fzf 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "fzf not found, installing via brew"
  brew install fzf || exit 1
  $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish || exit 1
fi

which trash 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "trash not found, installing via brew"
  brew install trash || exit 1
fi

which direnv 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "direnv not found, installing via brew"
  brew install direnv || exit 1
fi

which mise 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "mise not found, installing via brew"
  brew install mise || exit 1
fi

which just 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "just not found, installing via brew"
  brew install just || exit 1
fi

which rg 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "ripgrep not found, installing via brew"
  brew install ripgrep || exit 1
fi

which delta 2>&1 >/dev/null
if [ $? -ne 0 ]; then
  echo "git-delta not found, installing via brew"
  brew install git-delta || exit 1
fi

if [ ! -d ~/.config ]; then
  mkdir ~/.config
fi

if [ ! -d ~/.config/nvim ]; then
  echo "Linking nvim config"
  ln -sv $XRCDIR/nvim ~/.config
fi

if [ ! -d ~/.config/git ]; then
  echo "Linking git config"
  ln -sv $XRCDIR/git ~/.config
fi

if [ ! -d ~/.config/karabiner ]; then
  echo "Linking karabiner config"
  ln -sv $XRCDIR/karabiner ~/.config
fi

if [ ! -d ~/.config/ghostty ]; then
  echo "Linking ghostty config"
  ln -sv $XRCDIR/ghostty ~/.config
fi

for config in zshrc zshenv zlogin zimrc direnvrc; do
  if [ ! -h ~/.$config ]; then
    if [ -f ~/.$config ]; then
      echo "Preserving old .$config"
      mv -v ~/.$config ~/.$config.old
    fi
    echo "Linking .$config"
    ln -sv $XRCDIR/$config ~/.$config
  fi
done

# Launch zim install
source $XRCDIR/zim/zimfw.zsh install
