#!/bin/zsh

XRCDIR=$(cd `dirname $0` && pwd)

echo "Removing all traces of xrc"
rm -f ~/.config/nvim
rm -fr ~/.cache/dein
rm -f ~/.config/git
rm -f ~/.ctags
for config in zshrc zshenv zlogin zimrc; do
  rm -f ~/.$config
done
rm -fr $XRCDIR
